import{a as v,S,i as d}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function c(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=c(t);fetch(t.href,s)}})();async function g(o,e){const c="42236651-09dd8ef8cae726de85d6e38a7",r="https://pixabay.com",t="/api/",s={key:c,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e},i=`${r}${t}`;return(await v.get(i,{params:s})).data}function P(o){return o.hits.map(e=>` <a href="${e.largeImageURL}" class="image-card">
    <img src="${e.webformatURL}" alt="${e.tags}"/>
    <div class="caption">
    <ul class="caption-list"><li class="caption-text">Views <span>${e.views}</span></li>
    <li class="caption-text">Likes <span>${e.likes}</span></li>
    <li class="caption-text">Comments <span>${e.comments}</span></li>
    <li class="caption-text">Downloads <span>${e.downloads}</span></li>
    </ul>
    </div>
  </a>`).join("")}const $=document.querySelector("form"),u=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-btn"),x={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250};let f=new S(".gallery a",x);f.on("show.simplelightbox");let a,n,m;$.addEventListener("submit",E);p.addEventListener("click",O);async function E(o){if(o.preventDefault(),u.innerHTML="",n=1,a=o.target.elements.search.value.trim(),w(),!a){d.warning({title:"Caution",position:"topLeft",message:"This field is required"}),l();return}try{const e=await g(a,n);m=Math.ceil(e.total/15),L(e),f.refresh(),l(),T(),q(e)}catch(e){console.log(e)}o.target.reset()}function q(o){o.total||(d.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),h())}function L(o){const e=P(o);u.insertAdjacentHTML("beforeend",e)}async function O(o){h(),w(),n+=1;const e=await g(a,n);L(e),f.refresh(),l(),b(),M(),R()}function T(){n!=m&&b()}function M(){n>=m&&(h(),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function w(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}function b(){p.classList.remove("is-hidden")}function h(){p.classList.add("is-hidden")}function R(){const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:`${2*o}`})}
//# sourceMappingURL=commonHelpers.js.map
